### ISSUE TITLE
Add events calendar

### ISSUE THREAD

**Issue by alexgleason** [marykatefain/PhillyAnimalRightsAlliance#3]
Straight from the horse's mouth ( @marykatefain ):

>Form where approved people can submit their calendar of events; one event at a time. It would put those events with all their information: eg name of the event, date time/location, organization that's hosting it, link to the event page, and contact information.
>
>It would pull each of these fields into a spreadsheet/database and that database would be used to populate a calendar on the website. It would maybe even color-code things; ideally a monthly calendar where. Approved people from THL or whatever, their stuff would automatically go on. Other people who are not approved could submit events for approval which would then be approved and show on the calendar.
>
>Oh, and we want two calendars: one for activism and one for social events. Social events are really secondary and less priority.

**Comment by marykatefain** [comment]
- create JSON file from google submission form (FOS alternative?)
 (https://coderwall.com/p/duapqq/use-a-google-spreadsheet-as-your-json-backend)
- create calendar (https://fullcalendar.io) 
- pull JSON event data into calendar
- styles

**Comment by alexgleason** [comment]
The only FOSS alternative to Google Forms I'm aware of is to create your own custom form and save the submissions into your own database.

**Comment by alexgleason** [comment]
So there is [LimeSurvey](https://www.limesurvey.org/) but it costs money unless you self-host, it seems like total overkill, and getting information out of it is probably harder than writing your own form.
