### ISSUE TITLE
Needs a favicon and metadata info

### ISSUE THREAD

**Issue by alexgleason** [marykatefain/PhillyAnimalRightsAlliance#5]
Missing favicon (the icon in the tab bar).

Also should contain a meta description tag for search engines as well as opengraph meta tags for social sharing. See [my personal site](https://notabug.org/alexgleason/alexgleason-website/src/master/www/index.html) for an example.

This is important because it determines what text will display in a search engine as well as when you share the link on social media platforms.

You can use this tool to go from an SVG to icons of various shapes and sizes. http://realfavicongenerator.net/

**Comment by marykatefain** [comment]
Thanks for the example!
